apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: marketsummary
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary
        wait: true
        chartPath: ./charts/marketsummary
        values:
          image: marketsummary
        setValues:
          hpa.enabled: true
          canary.enabled: true
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"

profiles:
  - name: local
    build:
      artifacts:
        - image: 'artifactory.toolchain.lead.sandbox.liatr.io/docker-registry/joe-lab/marketsummary'
          context: .
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}'
    deploy:
      helm:
        releases:
          - name: marketsummary
            wait: true
            recreatePods: true
            chartPath: ./charts/marketsummary
            setValueTemplates:
              istioDomain: 'joe-lab-staging.lead.sandbox.liatr.io'
              image: '{{.IMAGE_NAME}}:latest'

